[package]
name = "aim_training"
version = "0.1.0"
authors = ["LucasGobbs <llcostagobbi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.4"
rlua = "0.17.0"
rand = "0.7.3"